import { Product, searchProducts, type SearchProductsParams } from '@lightspeed/ecom-headless'
import { ref, computed, onMounted, ComputedRef } from 'vue'

import { useInitStorefrontApi } from '../../init-storefront-api'
import type { ProductView } from '../../types/product'
import { getErrorMessage, logError } from '../../utils/error-handler'
import { useCurrentLanguage } from '../../utils/use-current-language'

/**
 * Extended Product type with additional fields from API
 * These fields exist in the API but aren't in official @lightspeed/ecom-headless types
 */
type ProductWithAdditionalFields = Product & {
	compareToPriceFormatted?: string
	ribbon?: {
		text: string
		color: string
	}
	thumbnailUrl?: string
	smallThumbnailUrl?: string
	hdThumbnailUrl?: string
	originalImageUrl?: string
	ribbonTranslated?: Record<string, { text: string; color: string }>
	hasFreeShipping?: boolean
	volume?: number
	nameYourPriceEnabled?: boolean
	// Note: rating and reviewsPublished fields are defined in Product type but not yet
	// returned by searchProducts API (as of @lightspeed/ecom-headless v1.1.1)
	// Will be available in future version when backend adds support
}

/**
 * Composable for fetching and managing products from Ecwid API
 *
 * @param filter - Optional filter function to filter products
 * @param limit - Maximum number of products to return (default: unlimited)
 * @returns Object with products data, loading state, and error state
 */
export function useProducts<T, S>(
	filter: (product: ProductWithAdditionalFields) => unknown = () => true,
	limit?: number,
) {
	const productsList = ref<ProductWithAdditionalFields[]>([])
	const isLoading = ref(true)
	const hasError = ref(false)
	const errorMessage = ref<string | null>(null)

	/**
   * Computed products with filtering and mapping
   * - Filters products based on provided filter function
   * - Limits to specified count (if provided)
   * - Maps to ProductView format
   */
	const products: ComputedRef<ProductView[]> = computed(() => {
		const filtered = productsList.value.filter((product) => filter(product))
		const limited = limit ? filtered.slice(0, limit) : filtered
		return limited.map((product) => ({
			// Core
			id: product.id,
			sku: product.sku,

			// Names
			name: product.name,
			subtitle: product.subtitle,
			subtitleTranslated: product.subtitleTranslated,
			description: product.description,

			// Pricing
			price: product.price,
			defaultDisplayedPrice: product.defaultDisplayedPrice,
			defaultDisplayedPriceFormatted: product.defaultDisplayedPriceFormatted,
			formattedPrice: product.defaultDisplayedPriceFormatted,
			compareToPrice: product.compareToPrice,
			compareToPriceFormatted: product.compareToPriceFormatted,
			compareToPriceDiscount: product.compareToPriceDiscount,
			compareToPriceDiscountFormatted: product.compareToPriceDiscountFormatted,
			compareToPriceDiscountPercent: product.compareToPriceDiscountPercent,
			compareToPriceDiscountPercentFormatted: product.compareToPriceDiscountPercentFormatted,

			// URLs and SEO
			url: product.url,
			autogeneratedSlug: product.autogeneratedSlug,
			customSlug: product.customSlug,
			seoTitle: product.seoTitle,
			seoDescription: product.seoDescription,

			// Images
			imageUrl: product.originalImage?.url,
			thumbnailUrl: product.thumbnailUrl,
			smallThumbnailUrl: product.smallThumbnailUrl,
			hdThumbnailUrl: product.hdThumbnailUrl,
			originalImageUrl: product.originalImageUrl,
			originalImage: product.originalImage,
			galleryImages: product.galleryImages,

			// Inventory
			inStock: product.inStock,
			outOfStock: !product.inStock,
			unlimited: product.unlimited,

			// Categories
			categoryIds: product.categoryIds,
			categories: product.categories,
			defaultCategoryId: product.defaultCategoryId,

			// Display
			isSampleProduct: product.isSampleProduct,
			enabled: product.enabled,
			showOnFrontpage: product.showOnFrontpage,

			// Ribbon
			ribbon: product.ribbon,
			ribbonTranslated: product.ribbonTranslated,

			// Reviews/Rating - Ready for future ecom-headless version
			// Currently returns undefined, will work when searchProducts API adds support
			averageRating: product.rating,
			reviewsCount: product.reviewsPublished,

			// Attributes
			attributes: product.attributes,
			options: product.options,
			combinations: product.combinations,

			// Shipping
			isShippingRequired: product.isShippingRequired,
			hasFreeShipping: product.hasFreeShipping,
			weight: product.weight,
			dimensions: product.dimensions,
			volume: product.volume,

			// Advanced
			isGiftCard: product.isGiftCard,
			discountsAllowed: product.discountsAllowed,
			nameYourPriceEnabled: product.nameYourPriceEnabled,
			relatedProducts: product.relatedProducts,

			// Timestamps
			created: product.created,
			updated: product.updated,
			createTimestamp: product.createTimestamp,
			updateTimestamp: product.updateTimestamp,
		}))
	})

	/**
   * Fetch products from Ecwid API
   * Handles errors and sets appropriate error messages
   */
	const fetchProducts = async (currentLanguage?: string) => {
		try {
			await useInitStorefrontApi()
			const params = (currentLanguage ? { lang: currentLanguage } : {}) as SearchProductsParams
			const response = await searchProducts({ ...params, enabled: true })
			productsList.value = (response.items || []) as ProductWithAdditionalFields[]
		} catch (error) {
			logError('useProducts.fetchProducts', error)
			hasError.value = true
			errorMessage.value = getErrorMessage(error)
		} finally {
			isLoading.value = false
		}
	}

	// Fetch products on mount
	onMounted(() => {
		const { currentLanguage } = useCurrentLanguage<T, S>()
		fetchProducts(currentLanguage.value)
	})

	return {
		products,
		isLoading,
		hasError,
		errorMessage,
		fetchProducts, // Expose for manual refetch if needed
	}
}
