import type { Category } from '@lightspeed/ecom-headless'
import { searchCategories } from '@lightspeed/ecom-headless'
import { ref, computed, onMounted, ComputedRef } from 'vue'

import { useInitStorefrontApi } from '../../init-storefront-api'
import { CategoryView } from '../../types/category'
import { getErrorMessage, logError } from '../../utils/error-handler'
import { useCurrentLanguage } from '../../utils/use-current-language'

/**
 * Extended Category type with additional fields from API
 */
type CategoryWithAdditionalFields = Category & {
	borderInfo?: {
		dominatingColor?: {
			red: number
			green: number
			blue: number
			alpha: number
		}
		homogeneity?: boolean
	}
	alt?: {
		main?: string
		translations?: Record<string, string>
	}
	isSampleCategory?: boolean
}

/**
 * Composable for fetching and managing categories from Ecwid API
 *
 * @param limit - Maximum number of categories to return (default: unlimited)
 * @param rootOnly - If true, only return root categories without parentId (default: true)
 * @returns Object with categories data, loading state, and error state
 */
export function useCategories<T, S>(limit?: number, rootOnly: boolean = true) {
	const categoriesList = ref<CategoryWithAdditionalFields[]>([])
	const isLoading = ref(true)
	const hasError = ref(false)
	const errorMessage = ref<string | null>(null)

	/**
   * Computed categories with filtering and mapping
   * - Filters out disabled categories
   * - Optionally filters out child categories (only root categories without parentId)
   * - Limits to specified count (if provided)
   * - Maps to CategoryView format
   */
	const categories: ComputedRef<CategoryView[]> = computed(() => {
		let filtered = categoriesList.value.filter((category) => category.enabled)

		if (rootOnly) {
			filtered = filtered.filter((category) => !category.parentId)
		}

		const limited = limit ? filtered.slice(0, limit) : filtered

		return limited.map((category) => ({
			// Core
			id: category.id,
			parentId: category.parentId,
			orderBy: category.orderBy,

			// Names
			name: category.name,
			nameTranslated: category.nameTranslated,
			description: category.description,
			descriptionTranslated: category.descriptionTranslated,

			// URLs
			url: category.url,
			autogeneratedSlug: category.autogeneratedSlug,
			customSlug: category.customSlug,

			// Images
			imageUrl: category.originalImageUrl || category.imageUrl,
			originalImageUrl: category.originalImageUrl,
			thumbnailUrl: category.thumbnailUrl,
			hdThumbnailUrl: category.hdThumbnailUrl,
			originalImage: category.originalImage,
			thumbnail: category.thumbnail,
			borderInfo: category.borderInfo,

			// SEO
			seoTitle: category.seoTitle,
			seoDescription: category.seoDescription,
			alt: category.alt,

			// Status
			enabled: category.enabled,
			productCount: category.productCount,
			isSampleCategory: category.isSampleCategory,
		}))
	})

	/**
   * Fetch categories from Ecwid API
   * Handles errors and sets appropriate error messages
   */
	const fetchCategories = async (currentLanguage?: string) => {
		try {
			await useInitStorefrontApi()
			const response = await searchCategories({ lang: currentLanguage })
			categoriesList.value = (response.items || []) as CategoryWithAdditionalFields[]
		} catch (error) {
			logError('useCategories.fetchCategories', error)
			hasError.value = true
			errorMessage.value = getErrorMessage(error)
		} finally {
			isLoading.value = false
		}
	}

	// Fetch categories on mount
	onMounted(() => {
		const { currentLanguage } = useCurrentLanguage<T, S>()
		fetchCategories(currentLanguage.value)
	})

	return {
		categories,
		isLoading,
		hasError,
		errorMessage,
		fetchCategories, // Expose for manual refetch if needed
	}
}
