/**
 * Category view model with all available fields from Ecwid API
 */
export type CategoryView = {
	// Core identification
	id: number
	parentId?: number
	orderBy?: number

	// Names and descriptions
	name: string
	nameTranslated?: Record<string, string>
	description?: string
	descriptionTranslated?: Record<string, string>

	// URLs and slugs
	url?: string
	autogeneratedSlug?: string
	customSlug?: string

	// Images
	imageUrl?: string
	originalImageUrl?: string
	thumbnailUrl?: string
	hdThumbnailUrl?: string
	originalImage?: {
		url: string
		width: number
		height: number
	}
	thumbnail?: {
		url: string
		width: number
		height: number
	}
	borderInfo?: {
		dominatingColor?: {
			red: number
			green: number
			blue: number
			alpha: number
		}
		homogeneity?: boolean
	}

	// SEO
	seoTitle?: string
	seoDescription?: string
	alt?: {
		main?: string
		translations?: Record<string, string>
	} | Record<string, string>

	// Status
	enabled?: boolean
	productCount?: number
	isSampleCategory?: boolean
}
