/**
 * Product view model for displaying products in the UI
 * Contains comprehensive data from Ecwid API
 */
export type ProductView = {
  // Core identification
  id: number
  sku?: string

  // Names and descriptions
  name: string
  subtitle?: string
  subtitleTranslated?: Record<string, string>
  description?: string

  // Pricing
  price?: number
  defaultDisplayedPrice?: number
  defaultDisplayedPriceFormatted: string
  formattedPrice: string

  // Compare pricing (for sales)
  compareToPrice?: number
  compareToPriceFormatted?: string
  compareToPriceDiscount?: number
  compareToPriceDiscountFormatted?: string
  compareToPriceDiscountPercent?: number
  compareToPriceDiscountPercentFormatted?: string

  // URLs and SEO
  url: string
  autogeneratedSlug?: string
  customSlug?: string
  seoTitle?: string
  seoDescription?: string

  // Images
  imageUrl?: string
  thumbnailUrl?: string
  smallThumbnailUrl?: string
  hdThumbnailUrl?: string
  originalImageUrl?: string
  originalImage?: {
    url: string
    width: number
    height: number
  }
  galleryImages?: Array<{
    url: string
    width: number
    height: number
    orderBy: number
  }>

  // Inventory
  inStock?: boolean
  outOfStock: boolean
  unlimited?: boolean

  // Categories
  categoryIds?: number[]
  categories?: Array<{
    id: number
    enabled: boolean
  }>
  defaultCategoryId?: number

  // Display flags
  isSampleProduct?: boolean
  enabled?: boolean
  showOnFrontpage?: number

  // Ribbon/badge
  ribbon?: {
    text: string
    color: string
  }
  ribbonTranslated?: Record<string, { text: string; color: string }>

  // Reviews/Rating - Ready for future ecom-headless version
  // Will be populated when searchProducts API adds support for rating/reviewsPublished fields
  averageRating?: number  // Average rating 0-5
  reviewsCount?: number  // Number of published reviews

  // Product attributes
  attributes?: Array<{
    id: number
    name: string
    value: string
    type: string
    show: string
  }>

  // Options and combinations
  options?: Array<{
    type: string
    name: string
    nameTranslated?: Record<string, string>
    choices: Array<{
      text: string
      textTranslated?: Record<string, string>
      priceModifier: number
      priceModifierType: string
    }>
    defaultChoice: number
    required: boolean
  }>
  combinations?: unknown[]

  // Shipping
  isShippingRequired?: boolean
  hasFreeShipping?: boolean
  weight?: number
  dimensions?: {
    length: number
    width: number
    height: number
  }
  volume?: number

  // Advanced features
  isGiftCard?: boolean
  discountsAllowed?: boolean
  nameYourPriceEnabled?: boolean

  // Related
  relatedProducts?: unknown

  // Timestamps
  created?: string
  updated?: string
  createTimestamp?: number
  updateTimestamp?: number
};
